# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# gazebo_ros_control/pid_gains:
#     joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     joint_3: {p: 20.0, i: 0.0, d: 0.0}
#     joint_4: {p: 20.0, i: 0.0, d: 0.0}
#     joint_5: {p: 20.0, i: 0.0, d: 0.0}
#     joint_6: {p: 20.0, i: 0.0, d: 0.0}
#     finger_1_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_1_joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     finger_2_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_2_joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     finger_middle_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_middle_joint_2: {p: 20.0, i: 0.0, d: 0.0}
# kinect/gazebo_ros_control/pid_gains:
#     joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     joint_3: {p: 20.0, i: 0.0, d: 0.0}
#     joint_4: {p: 20.0, i: 0.0, d: 0.0}
#     joint_5: {p: 20.0, i: 0.0, d: 0.0}
#     joint_6: {p: 20.0, i: 0.0, d: 0.0}
#     finger_1_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_1_joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     finger_2_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_2_joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     finger_middle_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_middle_joint_2: {p: 20.0, i: 0.0, d: 0.0}
# manip/gazebo_ros_control/pid_gains:
#     joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     joint_3: {p: 20.0, i: 0.0, d: 0.0}
#     joint_4: {p: 20.0, i: 0.0, d: 0.0}
#     joint_5: {p: 20.0, i: 0.0, d: 0.0}
#     joint_6: {p: 20.0, i: 0.0, d: 0.0}
#     finger_1_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_1_joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     finger_2_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_2_joint_2: {p: 20.0, i: 0.0, d: 0.0}
#     finger_middle_joint_1: {p: 20.0, i: 0.0, d: 0.0}
#     finger_middle_joint_2: {p: 20.0, i: 0.0, d: 0.0}
