kinect:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  kinect_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_torso_to_torso_sensor_plat
    pid: {p: 10.0, i: 0.0, d: 0.0}
