suport:
  # Publish all joint states -----------------------------------
  suporte_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  suporte_position_controller:
    type: effort_controllers/JointPositionController
    joint: suporte_joint
    pid: {p: 100.0, i: 1.0, d: 1.0}
