support:
  # Publish all joint states -----------------------------------
  support_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  support_position_controller:
    type: effort_controllers/JointPositionController
    joint: support_joint
    pid: {p: 100.0, i: 1.0, d: 1.0}
