kinect_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

kinect_controller:
  type: position_controllers/JointPositionController
  joint: joint_torso_to_torso_sensor_plat
  pid: {p: 20.0, i: 0.0, d: 0.0}

  
  # Position Controllers ---------------------------------------
  